# Generated by Django 4.1 on 2022-08-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.CharField(max_length=20, null=None)),
                ('template_index', models.CharField(default='index.html', max_length=20)),
            ],
        ),
    ]
